### ISSUE TITLE
Spawner doesn't break if it spawns non-living entity like fireworks or arrows

### ISSUE THREAD

**Issue by HerobrineXia** [Mrbysco/AgeingSpawners#2]
## Client Info
* Minecraft Version: 1.16.5

* Forge Version: 1.16.5-forge-36.1.0
* Mod Version: 1.1.0
* Java Version: 1.8.0

## Issue Description
Spawner doesn't break if it spawns non-living entity like fireworks

## Reproduce Steps
1. Place a spawner and set its SpawnData/SpawnPotentials to firework entity.

## Additional Information
<img width="867" alt="image" src="https://user-images.githubusercontent.com/35889828/123059930-d9139e80-d43c-11eb-82fc-8f2783fb70ca.png">
I think it could be because of these entities are not living entity.

**Comment by LTCatt** [comment]
This issue affects _when dungeons arise_ mod.
https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise
The mob spawners generated in this mod actually spawns a firework, and the monster rides on the firework. So these spawners won't be destroyed.

**Comment by LTCatt** [comment]
Could you tell me this problem will be fixed soon or not?
My modpack is about to be released, but because of this issue, players can farm monsters, which breaks the balance...
I'm waiting for it to be fixed so long...

**Comment by Mrbysco** [comment]
I'm still looking into it. The event I rely on only fires for entities that extend MobEntity. Which the firework obviously doesn't. So I have to figure out another way
